blueprint:
  name: Notification to Close a Window/door
  description: Notification to close windows/doors
  domain: automation
  input:
    contact_sensor:
      name: Contact Sensor
      description: The window or door sensor that triggers the automation.
      selector:
        entity:
          domain: binary_sensor
          multiple: false
    first_timer:
      name: First timer
      description: The first notification timer (in minutes).
      default: 10
      selector:
        number:
          min: 1.0
          step: 1.0
          max: 60.0
          mode: slider
    second_timer:
      name: Second timer
      description: The second notification timer (in minutes).
      default: 15
      selector:
        number:
          min: 1.0
          step: 1.0
          max: 60.0
          mode: slider
    device_identifier:
      name: Device to notify
      description:
        "The device to receive the notification; it needs to run the official  Home
        Assistant app to receive notifications.
        "
      selector:
        entity:
          domain: media_player
          multiple: false
trigger:
  - platform: state
    entity_id: !input contact_sensor
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: !input first_timer
      seconds: 0
  - platform: state
    entity_id: !input contact_sensor
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: !input second_timer
      seconds: 0
condition:
  - condition: state
    entity_id: !input contact_sensor
    state: "on"
action:
  - alias: Home Assistant Default tts.google_translate_say selected
    service: tts.google_translate_say
    data:
      entity_id: !input "speaker_target"
      message: "Time to close {{trigger.to_state.attributes.friendly_name}}."
mode: single
